version: '3.7'
services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3002:3002
    secrets:
      - DATABASE_URL

  db:
    image: mariadb:10.5.8
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: amms2
      MYSQL_PASSWORD: amms2
      MYSQL_DATABASE: amms2
    volumes:
      - db-volume:/var/lib/mysql
      - ./data/test-data.sql:/docker-entrypoint-initdb.d/test-data.sql
    depends_on:
      - node

networks:
  default:
    driver: bridge
secrets:
  DATABASE_URL:
    file: secrets/DATABASE_URL

volumes:
  db-volume: