---

services:
  app:
    build: .
    restart: always
    ports:
      - 3002:3002
    secrets:
      - DATABASE_URL

  db:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_DATABASE=amms2
      - MYSQL_PASSWORD=amms2
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=amms2
    volumes:
      - db-volume:/var/lib/mysql
      - ./data/test-data.sql:/docker-entrypoint-initdb.d/test-data.sql
    depends_on:
      - app

networks:
  default:
    driver: bridge

secrets:
  DATABASE_URL:
    file: secrets/DATABASE_URL

volumes:
  db-volume:
