name: Docker Compose Build and Run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-docker@v1

      - name: Build Docker images
        run: docker-compose build

      - name: Run Docker containers
        run: docker-compose up -d